#!/bin/sh
chmod +x win2unix
./win2unix
rm config.h
rm configure
rm Makefile
rm Makefile.in
rm src/Makefile
rm src/Makefile.in
rm config.h.in
rm aclocal.m4
rm -rf autom4te.cache
rm config.log
rm config.h.in~
rm config.status
rm configure.in.save
rm stamp-h
rm stamp-h1
rm stamp-h.in
cp /usr/share/automake*/missing .
cp /usr/share/automake*/depcomp .
cp /usr/share/automake*/mkinstalldirs .
cp /usr/share/automake*/install-sh .
aclocal
autoheader
autoconf
automake
